sudo: required
dist: trusty
addons:
  chrome: stable
language: node_js
node_js:
  - 'lts/*'
install:
  - npm i npm@6.1.0
  - npm ci
script:
  - npm run lint:eslint
  - npm run lint:stylelint
  - npm run build
#  - npm run test
# before_script:
#   - "sudo chown root /opt/google/chrome/chrome-sandbox"
#   - "sudo chmod 4755 /opt/google/chrome/chrome-sandbox"
#   - "export DISPLAY=:99.0"
#   - "sh -e /etc/init.d/xvfb start"
#   - sleep 3 # give xvfb some time to start
